spring.application.name=festival
server.port=8080

spring.datasource.url=jdbc:h2:mem:festivaldb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

swcf.api.key.facility=${SWCF_API_KEY_FACILITY}
swcf.api.key.fortress-story=${SWCF_API_KEY_FORTRESS_STORY}
swcf.api.key.palace-facility=${SWCF_API_KEY_PALACE_FACILITY}
swcf.api.key.palace-story=${SWCF_API_KEY_PALACE_STORY}
swcf.api.key.performance=${SWCF_API_KEY_PERFORMANCE}
swcf.api.key.experience=${SWCF_API_KEY_EXPERIENCE}
swcf.api.key.theme=${SWCF_API_KEY_THEME}
swcf.api.key.event=${SWCF_API_KEY_EVENT}
swcf.api.key.education=${SWCF_API_KEY_EDUCATION}

